import Head from "next/head";
import Navbar from "./components/navbar";
import MainBanner from "./components/main-banner";
import TeamsBox from "./components/teams";
import HeroImageBox from "./components/hero-image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stitches Crash Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <MainBanner />
        <TeamsBox />
        <HeroImageBox/>
      </main>
    </>
  );
}
